apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-netbird
  namespace: cluster-infra-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: infra
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.12.2
    helm:
      valuesObject:
        controller:
          replicaCount: 3
          ingressClassByName: true
          ingressClassResource:
            controllerValue: k8s.io/ingress-nginx-netbird
            name: nginx-netbird
            default: true
          ingressClass: nginx-netbird
          extraArgs:
            default-ssl-certificate: ingress-nginx-netbird/wildcard-internal-tls
          service:
            type: ClusterIP
            annotations:
              netbird.io/expose: "true"
              netbird.io/policy: default
              netbird.io/resource-name: netbird-nginx
              netbird.io/groups: netbird-nginx-k8s
          metrics:
            enabled: false
            serviceMonitor:
              enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx-netbird
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
