apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: cluster-infra-argocd
spec:
  source:
    helm:
      valuesObject:
        cni:
          exclusive: true
          
        ipam:
          mode: kubernetes

        externalIPs:
          enabled: true

        kubeProxyReplacement: true

        k8sServiceHost: 10.24.0.5
        k8sServicePort: 6443

        ipv4NativeRoutingCIDR: 10.240.0.0/16