# helm upgrade --install cilium cilium/cilium --namespace kube-system -f /Users/david/Developer/shoal2/gitops/infra/network/cilium/overlays/tetra/raw.yaml
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
cni:
  exclusive: true
externalIPs:
  enabled: true
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: 10.240.0.0/16
ipv6:
  enabled: false
k8sClientRateLimit:
  burst: 100
  qps: 50
k8sServiceHost: 10.24.0.5
k8sServicePort: 6443
kubeProxyReplacement: true
l2announcements:
  enabled: false
  leaseDuration: 10s
  leaseRenewDeadline: 7s
  leaseRetryPeriod: 2s
securityContext:
  capabilities:
    ciliumAgent:
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    cleanCiliumState:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE