apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-node-exporter
  namespace: cluster-infra-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: infra
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-node-exporter
    targetRevision: 4.51.1
    helm:
      valuesObject:
        extraArgs:
          - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|run|var/lib/kubelet/.+|var/lib/containerd/.+|system)($|/)
          - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs|tmpfs)$
          - --collector.netclass.ignored-devices=^(veth.*)$
        tolerations:
          - operator: Exists
        prometheus:
          monitor:
            enabled: true
            relabelings:
            - sourceLabels:
                - __meta_kubernetes_pod_node_name
              targetLabel: node
              action: replace
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-observability-node-exporter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
