apiVersion: v1
kind: Pod
metadata:
  name: ceph-disk-cleanup
  namespace: rook-ceph
spec:
  hostNetwork: true
  hostPID: true
  containers:
  - name: disk-cleanup
    image: quay.io/ceph/ceph:v19.2.2
    command: ["/bin/bash"]
    args: ["-c", "sleep 3600"]
    securityContext:
      privileged: true
      capabilities:
        add: ["SYS_ADMIN"]
    volumeMounts:
    - name: dev
      mountPath: /dev
    - name: sys
      mountPath: /sys
    - name: run-udev
      mountPath: /run/udev
  volumes:
  - name: dev
    hostPath:
      path: /dev
  - name: sys
    hostPath:
      path: /sys
  - name: run-udev
    hostPath:
      path: /run/udev
  nodeSelector:
    kubernetes.io/hostname: kf-op-barracuda-03
  tolerations:
  - operator: Exists
  restartPolicy: Never