---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare_api_token: AgAVMh8/o/9BG1U2KimWv0E8U9KHtGxtMdZKg4jtjXfyMuhpvhtUujUCx0+ZrDl53Nid57Ah0n/4fd+mVkPAcIrT1TK1+AWgndy+VKjLmh9fcUAlv8SoZ8iFCpXC50nO+KRbmZjfmC9ZECM2G2rMZCx7DuTILrkDJmE2HytLD85mV92VZ31/uFnaStgeOZ8Mn98NfyY6LQD6ulC3/lsO734jIoyBD6a0fqVVyOb1j77NDLDGhlz0hnMHFSICUq0dA9nukB4xGobm8HTm3/0Mtbbi9v1fkMte1PRZY8gXsHqq3UX4e9iXgYv1WFSCj/fcx3mz+sZzLhIqUib+IM5MgNLulSON+cUXyCqj5evpxMOx5oSb4yv1pSv83JL1Ha7Hv4cdcDwfC/+dbHp1XoHMPhIZS33wJkPzV0vHSjf/Ik2f8l58eS2AyVb4Hu9Wxbx5gb9X6u6IQKHGjWpGnlQaM2B0mCzVh6r1+tnDvSLbL1Qj/EyWQQjw6tEN60ojtVgQylkYkIJdt6Z9wCZ4JAYNHt9cOD3l1FcIceIAA2E4uYrx73ITcqaNFiD+TC88piJkMxLW09qLN1OvhRZ2JwNdHTUchs270X+FLHYF/X6mCxMb+h5lXFgtpCis6XLcwdctTRIsUWpd6iU19BaAnLIA9HwHjKjeAALoVVjcaG4GHrNEFazW+IxBptpRBVMDRWTctfea88iiTC276tRjH62NalI6dDUzPYIBkQEakHtwpwNi/+juBI3gK49J
  template:
    metadata:
      name: cloudflare
      namespace: cert-manager
    type: Opaque
