# curl https://storage.googleapis.com/kubevirt-prow/release/kubevirt/kubevirt/stable.txt
resources:
  - https://github.com/kubevirt/kubevirt/releases/download/v1.5.2/kubevirt-operator.yaml
  - https://github.com/kubevirt/kubevirt/releases/download/v1.5.2/kubevirt-cr.yaml
