apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcloud-csi
  namespace: cluster-infra-argocd
spec:
  project: infra
  source:
    repoURL: https://charts.hetzner.cloud
    chart: hcloud-csi
    targetRevision: 2.19.0
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
