apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  # renovate: datasource=github-releases depName=kubernetes-csi/external-snapshotter
  - https://github.com/kubernetes-csi/external-snapshotter/client/config/crd?ref=v8.1.0
  # renovate: datasource=github-releases depName=kubernetes-csi/external-snapshotter
  - https://github.com/kubernetes-csi/external-snapshotter/deploy/kubernetes/snapshot-controller?ref=v8.1.0

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: snapshot-controller
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: kube-system
  - target:
      version: v1
      kind: ServiceAccount
      name: snapshot-controller
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: kube-system
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: snapshot-controller-role
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: kube-system