# helm install cilium cilium/cilium --version 1.18.0 --namespace kube-system -f values.yaml

ipam:
  mode: kubernetes

kubeProxyReplacement: true

routingMode: native

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

k8sServiceHost: localhost
k8sServicePort: 7445

devices: br1

ipv4NativeRoutingCIDR: 10.244.0.0/16

autoDetectMTU: enabled

bandwidthManager:
  enabled: true

localRedirectPolicy: true

ipv4:
  enabled: true

enableIPv4Masquerade: true

ipMasqAgent:
  enabled: false

hubble:
  relay:
    enabled: true
  ui:
    enabled: true

bpf:
  mapDynamicSizeRatio: 0.25
  masquerade: true

healthChecking: true

identityAllocationMode: crd

prometheus:
  enabled: true