apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: cluster-infra-argocd
spec:
  source:
    helm:
      valuesObject:
        controller:
          nodeSelector:
            node-role.kubernetes.io/control-plane: ""
          kind: DaemonSet
          hostNetwork: true
          hostPort:
            enabled: true