apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
spec:
  project: infra
  source:
    repoURL: https://charts.rook.io/release
    chart: rook-ceph
    targetRevision: 0.31.0
    # helm:
    #  values: 
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true