---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config
data:
  deployment: |
    metadata:
      labels:
        app: istio-ingress
        istio: ingressgateway
        Istio: ingressgateway
        release: istio-ingress
  horizontalPodAutoscaler: |
    spec:
      minReplicas: 1
      maxReplicas: 2
  service: |
    spec:
      ports:
      - $patch: delete
        port: 15021