apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "br0",
      "isDefaultGateway": false,
      "hairpinMode": true,
      "ipMasq": false,
      "ipam": {
        "type": "host-local",
        "subnet": "10.0.1.0/24",
        "rangeStart": "10.0.1.200",
        "rangeEnd": "10.0.1.250",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "10.0.1.254"
      }
    }'