apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-conf
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "bridge-conf",
      "type": "bridge",
      "bridge": "br0",
      "isDefaultGateway": false,
      "hairpinMode": true,
      "ipMasq": false,
      "ipam": {
        "type": "whereabouts",
        "range": "10.0.1.0/24",
        "range_start": "10.0.1.200",
        "range_end": "10.0.1.250",
        "gateway": "10.0.1.254",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ]
      }
    }'