apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # renovate: datasource=github-releases depName=kubevirt/kubevirt
  - https://github.com/kubevirt/kubevirt/releases/download/v1.5.2/kubevirt-operator.yaml
  - kubevirt.yaml
  # renovate: datasource=github-releases depName=kubevirt/containerized-data-importer  
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.62.0/cdi-operator.yaml
  - cdi.yaml