apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8up
  namespace: cluster-infra-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: infra
  source:
    repoURL: https://k8up-io.github.io/k8up
    chart: k8up
    targetRevision: 4.8.4
    helm:
      valuesObject:
        k8up:
          operatorNamespace: k8up
  destination:
    server: https://kubernetes.default.svc
    namespace: k8up
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true