apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: cluster-infra-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: infra
  source:
    # https://github.com/helm/helm/issues/13466
    repoURL: registry-1.docker.io/bitnamicharts
    chart: external-dns
    targetRevision: 9.0.2
    helm:
      valuesObject:
        txtPrefix: extdns
        provider: cloudflare
        registry: noop
        cloudflare:
          secretName: cloudflare
          proxied: false
        extraArgs:
          "annotation-filter": "external-dns.alpha.kubernetes.io/hostname"
          "exclude-target-net": "10.0.0.0/8"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true