---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgCAiXxAbZkqOYMMpNtaujTbuFybyLGTObhrGpgFcrKLJHorKWkDY+7InsPnDxYofpdIIQ1IvOW7DBC0JV/mYMnc7AcFJjafaK/ZFPLNoQ0sSTyZPanA2eGw5piErMZfbAi2V9qDvozPxfiHFfJhf6sMlLYhQNgYFkYLrIZq9GOwiXSWco1PqXuvMz1zwuCs/Mu6PGOWjLORb4dctml2ruzSMRDwEMCBUcavHKlJxDIdsTRsqkvL8T81H39glriePrfPOzCfe+5ehMPHMk+6pg0UAWr8kEsD3oqJIJCmzYhYKu+ZndaKa9mdF8a1Tq/RNLNPuR3xWOnuhbGl+nnnW8YqLuMlQG63VJHeLcFuj1Nyso3cHXZhjp4BKL3uqg6D5Wc4nd5PtTwMvOyVBJwe88itT3IJctf1aHbeWxfyF46w12v2zUq16cR5P8814uFjvwRLp81nM4ao7fP0R6sg2VBAEIOp8DuSL5L1ijMaAbLR3F50tg69ir4bXlWmLBceHmTI2vLB2R8BYBjKsndmPbt6UMUIQskS8qqEt4q8PF6Ukq1ELgsc+LSyjsq8LbtWzYOqyO907ZUIZB3aesIEDYdbaiLQYiGgvUaD7owANf1oYICUHY6et1zDMjgLx7AjGZPPkFs8DcJEofgXe1H5vYD4ebBLKPDmI63ZeWHl/SMxi55NwJvUCuZN1s48zIeIDTx0hcHqi70ZZ9HJds+1dVhrpq9QRzYxa/BIH/Z0dTe7nIdgjFWiTy+/
  template:
    metadata:
      name: cloudflare
      namespace: external-dns
    type: Opaque
