apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  namespace: cluster-argocd
spec: 
  # disableAdmin: true
  server:
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false

  sourceNamespaces: []