apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: cluster-infra-argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: 'https://kubernetes.default.svc'
  sourceNamespaces:
  - '*'
  sourceRepos:
  - '*'