apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: cluster-infra-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: infra
  source:
    repoURL: https://helm.cilium.io/
    chart: cilium
    targetRevision: "1.18.5"
    helm:
      valuesObject:
        ipam:
          mode: kubernetes

        routingMode: native
        tunnelProtocol: ""
        autoDirectNodeRoutes: true

        devices:
          - br1
          - enp3s0

        bpf:
          masquerade: true

        bgpControlPlane:
          enabled: false

        l2announcements:
          enabled: true

        externalIPs:
          enabled: true

        kubeProxyReplacement: true

        socketLB:
          hostNamespaceOnly: true

        cgroup:
          autoMount:
            enabled: false
          hostRoot: /sys/fs/cgroup

        k8sServiceHost: 127.0.0.1
        k8sServicePort: 7445

        ipv6:
          enabled: false

        ipv4NativeRoutingCIDR: 10.244.0.0/16

        hubble:
          enabled: true
          relay:
            enabled: true
          ui:
            enabled: true

        securityContext:
          capabilities:
            ciliumAgent:
              - CHOWN
              - KILL
              - NET_ADMIN
              - NET_RAW
              - IPC_LOCK
              - SYS_ADMIN
              - SYS_RESOURCE
              - DAC_OVERRIDE
              - FOWNER
              - SETGID
              - SETUID
            cleanCiliumState:
              - NET_ADMIN
              - SYS_ADMIN
              - SYS_RESOURCE
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true