apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    domain:
      "app.konst.fish": ""
    network:
      ingress-class: "gateway-api.ingress.networking.knative.dev"
      defaultExternalScheme: "https"
      # TODO: something like this: https://bsideup.github.io/posts/knative_custom_domains/ super cool
      domain-template: "{{.Name}}.{{.Domain}}"
      autocreate-cluster-domain-claims: "true"
    observability:
      metrics.backend-destination: "prometheus"

    # handled by config-gateway-patch.yaml rn
    gateway:
      external-gateways: |
        - class: istio
          gateway: istio-ingress/http-gateway
          service: istio-ingress/http-gateway-istio
          supported-features:
            - HTTPRouteRequestTimeout
      local-gateways: |
        - class: istio
          gateway: istio-ingress/http-gateway
          service: istio-ingress/http-gateway-istio
          supported-features:
            - HTTPRouteRequestTimeout
  # ingress:
  #   istio:
  #     enabled: true
  #     knative-ingress-gateway:
  #       selector:
  #         gateway.networking.k8s.io/gateway-name: http-gateway
  #       servers:
  #       - hosts:
  #         - "*.app.konst.fish"
  #         port:
  #           name: http
  #           number: 80
  #           protocol: HTTP
  #       - hosts:
  #         - "*.app.konst.fish"
  #         port:
  #           name: https
  #           number: 443
  #           protocol: HTTPS
  #         tls:
  #           mode: SIMPLE
  #           credentialName: wildcard-external-tls
  #     knative-local-gateway:
  #       selector:
  #         gateway.networking.k8s.io/gateway-name: http-gateway
  #       servers:
  #       - port:
  #           number: 80
  #           name: http
  #           protocol: HTTP
  #         hosts:
  #         - "*"