apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: provision
  namespace: cluster-infra-argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: 'https://kubernetes.default.svc'
  sourceNamespaces:
  - 'cluster-provisioning'
  sourceRepos:
  - '*'