apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argo-ns.yaml
  - argo-rb.yaml
  - argo-rb-cluster-app-reader.yaml
  - argo-appproj-infra.yaml
  - argo-appproj-provision.yaml