apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: olm
  namespace: cluster-infra-argocd
spec:
  project: infra
  source:
    repoURL: ghcr.io/cloudtooling/helm-charts
    chart: olm
    targetRevision: 0.32.0
    helm:
      valuesObject:
        namespace: olm
        catalog_namespace: olm
        operator_namespace: operators
  destination:
    server: https://kubernetes.default.svc
    namespace: olm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true