apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbird-operator
  namespace: cluster-infra-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: infra
  source:
    repoURL: https://netbirdio.github.io/kubernetes-operator
    chart: kubernetes-operator
    targetRevision: 0.2.0
    helm:
      valuesObject:
        ingress:
          enabled: true
          allowAutomaticPolicyCreation: false
          router:
            enabled: true
          kubernetesAPI:
            enabled: true
            policies:
              - cluster-api-access
          policies:
            cluster-api-access:
              name: "Barracuda Kubernetes API Access Policy"
              sourceGroups:
                - shoal-konst-fish:facultative
              ports:
                - 443
              protocols:
                - tcp
              bidirectional: false
            proxy-access:
              name: "Barracuda Proxy Access Policy"
              sourceGroups:
                - shoal-konst-fish:facultative
              ports:
                - 80
                - 443
              protocols:
                - tcp
              bidirectional: false
            proxy-access-public:
              name: "Barracuda Proxy Access Public Policy"
              sourceGroups:
                - barracuda-proxy-public
              ports:
                - 80
                - 443
              protocols:
                - tcp
              bidirectional: false
        cluster:
          dns: svc.barracuda.local
          name: barracuda
        netbirdAPI:
          keyFromSecret:
            name: "netbird-mgmt-api-key"
            key: "NB_API_KEY"
        managementURL: "https://netbird.konst.fish:443"
        webhook:
          failurePolicy: Ignore
  destination:
    server: https://kubernetes.default.svc
    namespace: netbird-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/warn: privileged
