apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: global-redirect
  namespace: istio-ingress
spec:
  parentRefs:
  - name: http-gateway
    sectionName: http
  hostnames:
  - "*.konst.fish"
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301