apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: transmission-redirect
spec:
  parentRefs:
  - name: http-gateway-netbird
    namespace: istio-ingress
    sectionName: http
  hostnames:
  - "transmission.barracuda.net.konst.fish"
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: transmission
spec:
  parentRefs:
  - name: http-gateway-netbird
    namespace: istio-ingress
    sectionName: https
  hostnames:
  - "transmission.barracuda.net.konst.fish"
  rules:
  - backendRefs:
    - name: transmission
      port: 9091
