apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8up
  namespace: cluster-infra-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: infra
  source:
    repoURL: https://k8up-io.github.io/k8up
    chart: k8up
    targetRevision: 4.8.4
    helm:
      valuesObject:
        k8up:
          operatorNamespace: k8up
          envVars:
            - name: BACKUP_GLOBALACCESSKEYID
              valueFrom:
                secretKeyRef:
                  name: k8up-global-s3-credentials
                  key: ACCESS_KEY_ID
            - name: BACKUP_GLOBALSECRETACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: k8up-global-s3-credentials
                  key: SECRET_ACCESS_KEY
            - name: BACKUP_GLOBALS3BUCKET
              valueFrom:
                secretKeyRef:
                  name: k8up-global-s3-credentials
                  key: bucket
            - name: BACKUP_GLOBALS3ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: k8up-global-s3-credentials
                  key: endpoint
            - name: BACKUP_GLOBALREPOPASSWORD
              valueFrom:
                secretKeyRef:
                  name: k8up-global-s3-credentials
                  key: RESTIC_PASSWORD
  destination:
    server: https://kubernetes.default.svc
    namespace: k8up
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true