apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-github-credentials
  namespace: dex-gh
spec:
  refreshInterval: 96h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: dex-github-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: auth_konst_fish_gh_app