---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config
data:
  deployment: |
    metadata:
      labels:
        app: istio-ingress
        istio: ingressgateway
        Istio: ingressgateway
        release: istio-ingress
  horizontalPodAutoscaler: |
    spec:
      minReplicas: 2
      maxReplicas: 5
  service: |
    metadata:
      annotations:
        load-balancer.hetzner.cloud/location: nbg1
        load-balancer.hetzner.cloud/name: ingress-istio-tetr
        load-balancer.hetzner.cloud/use-private-ip: "true"
        load-balancer.hetzner.cloud/uses-proxyprotocol: "false"
    spec:
      ports:
      - $patch: delete
        port: 15021