apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cluster-infra-argocd

resources:
  - ../../base
  # renovate: datasource=github-releases depName=argoproj/argo-cd
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.0.11/manifests/core-install.yaml

#patches:
#  - target:
#      kind: ConfigMap
#      name: argocd-cmd-params-cm
#    patch: |-
#      - op: add
#        path: /data
#        value:
#          application.namespaces: "cluster-infra-argocd,cluster-provisioning"