apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kiali-redirect
spec:
  hostnames:
  - "kiali.tetra.net.konst.fish"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kiali
spec:
  hostnames:
  - "kiali.tetra.net.konst.fish"